development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: muneris_development
  username: rubystack
  password: kanoka
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: muneris_test
  username: rubystack
  password: kanoka
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: muneris_production
  username: rubystack
  password: kanoka
  host: 127.0.0.1
  port: 3306